package com.luiza.models;

import java.sql.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * An entity User composed by three fields (id, email, firstName,lastName,sex).
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 *
 * @author Luiza
 */
@Entity
@Table(name = "users")
public class User {

 
  
  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;
  
  // The user's email
  @NotNull
  private String email;
  
  //The users's password
  @NotNull
  private String password;
  
  // The user's firstname
  @NotNull
  private String firstName;
  
//The user's lastname
 @NotNull
 private String lastName;
 
 
//The users's sex
@NotNull
private String sex;



  // ------------------------
  // PUBLIC METHODS
  // ------------------------
  
  public User() { }

  
 

  public User(String email, String password, String firstName, String lastName, String sex) {
	super();
	this.id = id;
	this.email = email;
	this.password = password;
	this.firstName = firstName;
	this.lastName = lastName;
	this.sex = sex;
}




public User(long id) {
	super();
	this.id = id;
}




public long getId() {
	return id;
}




public void setId(long id) {
	this.id = id;
}




public String getEmail() {
	return email;
}




public void setEmail(String email) {
	this.email = email;
}




public String getPassword() {
	return password;
}




public void setPassword(String password) {
	this.password = password;
}




public String getFirstName() {
	return firstName;
}




public void setFirstName(String firstName) {
	this.firstName = firstName;
}




public String getLastName() {
	return lastName;
}




public void setLastName(String lastName) {
	this.lastName = lastName;
}




public String getSex() {
	return sex;
}




public void setSex(String sex) {
	this.sex = sex;
}



 
  
} // class User